name: AutoDeploy

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: Node环境
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - name: 安装依赖
        run: npm install

      - name: 打包构建
        run: npm run build

      - name: 执行部署
        uses: Dacong-wu/sftp-deploy-action@main
        with:
          SFTP_HOST: ${{ secrets.HOST }}
          SFTP_USERNAME: ${{ secrets.USER_NAME }}
          SFTP_PASSWORD: ${{ secrets.USER_PASSWORD }}
          SFTP_REMOTE: ${{secrets.REMOTE}}
          BACKUP: false
